# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/travel_db
spring.datasource.username=postgres
spring.datasource.password=${POSTGRES_PASSWORD:mysecretpassword}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA : switched to validate to prevent filghting flyway o it's own and change schema which breaks migrations and auditability now it's controlled by flyway migration
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Flyway
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=false
spring.flyway.locations=classpath:db/migration
spring.flyway.validate-migration-naming=true

# Server
server.port=8081

# Logging
logging.level.org.hibernate.SQL=DEBUG
# less noisy than trace for normal development
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=DEBUG

# JWT
jwt.secret=mySuperSecretKeyForJWTGenerationThatIsAtLeast256BitsLong
# 24 hours in milliseconds 900000 for normal setup
jwt.expiration=60000

# Google OAuth2
spring.security.oauth2.client.registration.google.client-id=25289075777-ab18tekbddufodvhlvdoi7fnj5qrgvo8.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,profile,email

# Where backend redirects after OAuth success (your Next.js route)
app.oauth2.frontend-redirect=http://localhost:3000/auth/oauth-callback